# Generated by Django 3.2.13 on 2022-06-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='table',
            field=models.FileField(blank=True, null=True, upload_to='static/img/table/'),
        ),
    ]
