# Generated by Django 3.2.13 on 2022-06-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='table',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
    ]
